apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: connector-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: dbhistory
          patternType: prefix
        operation: Read
      - resource:
          type: topic
          name: dbhistory
          patternType: prefix
        operation: Write
      - resource:
          type: topic
          name: dbhistory
          patternType: prefix
        operation: Create
      - resource:
          type: cluster
        operation: AlterConfigs
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
