apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: example-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # access to kafka topic [Write]
      - resource:
          type: topic
          name: example-topic
          patternType: literal
        operation: Write
        host: "*"
      # access to kafka topic [Read]
      - resource:
          type: topic
          name: example-topic
          patternType: literal
        operation: Read
        host: "*"
      # access to kafka topic [Create]
      - resource:
          type: topic
          name: example-topic
          patternType: literal
        operation: Create
        host: "*"




