apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-prd
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 3
  authentication:
    type: scram-sha-512
    username: connect-user
    passwordSecret:
      secretName: sc-connect-user
      password: pwd-info
  bootstrapServers: 10.7.37.202:9094
  config:
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  build:
    output:
      type: docker
      image: netzoundx/strimzi-sqlconnect
      pushSecret: netzoundx-sc
    plugins:
      - name: debezium-sqlserver-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-sqlserver/1.7.0.Final/debezium-connector-sqlserver-1.7.0.Final-plugin.tar.gz
