apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
     metallb.universe.tf/allow-shared-ip: smart
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
         type: scram-sha-512
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        authentication:
         type: scram-sha-512
        configuration:
          bootstrap:
            loadBalancerIP: 10.255.0.22
          brokers:
          - broker: 0
            loadBalancerIP: 10.255.0.23
          - broker: 1
            loadBalancerIP: 10.255.0.24
          - broker: 2
            loadBalancerIP: 10.255.0.25
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.1"
      inter.broker.protocol.version: "3.1"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

